name: Check and Build

on:
  workflow_call:

jobs:
  lint:
    name: Spotless check
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Make Gradle executable
        run: |
          tr -d '\r' < gradlew > gradlew.tmp && mv gradlew.tmp gradlew
          chmod +x ./gradlew

      - name: Spotless
        run: ./gradlew spotlessCheck

  build:
    needs: lint
    if: ${{ needs.lint.result == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make Gradle executable
        run: |
          tr -d '\r' < gradlew > gradlew.tmp && mv gradlew.tmp gradlew
          chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew buildDevDebug
