name: Close Jira issue

on:
  workflow_call:
    secrets:
      ANDROID_JIRA_BASE_URL:
        required: true
      ANDROID_JIRA_API_TOKEN:
        required: true
      ANDROID_JIRA_USER_EMAIL:
        required: true

jobs:
  close-issue:
    name: Close Jira issue
    runs-on: self-hosted

    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.ANDROID_JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.ANDROID_JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.ANDROID_JIRA_USER_EMAIL }}

      - name: Extract Jira issue key from GitHub issue title
        id: extract-key
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          JIRA_KEY=$(echo "$ISSUE_TITLE" | grep -oE '[A-Z]+-[0-9]+')
          echo "JIRA_KEY=$JIRA_KEY" >> $GITHUB_ENV

      - name: Close Jira issue
        if: env.JIRA_KEY != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.JIRA_KEY }}
          transition: Done