name: Create Jira issue

on:
  workflow_call:
    secrets:
      ANDROID_JIRA_BASE_URL:
        required: true
      ANDROID_JIRA_API_TOKEN:
        required: true
      ANDROID_JIRA_USER_EMAIL:
        required: true

jobs:
  create-issue:
    name: Create Jira issue
    runs-on: self-hosted
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.ANDROID_JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.ANDROID_JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.ANDROID_JIRA_USER_EMAIL }}

      - name: Check out code
        uses: actions/checkout@v6

      - name: Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/issue-template.yml

      - name: Log Issue Parser
        run: |
          echo '${{ steps.issue-parser.outputs.issueparser_parentKey }}'
          echo '${{ steps.issue-parser.outputs.__ticket_number }}'
          echo '${{ steps.issue-parser.outputs.jsonString }}'

      - name: Convert markdown to Jira Syntax
        uses: peter-evans/jira2md@v3
        id: md2jira
        with:
          input-text: |
            ### Github Issue Link
            - ${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}
          mode: md2jira

      - name: Build fields JSON
        id: issue-fields
        run: |
          ASSIGNEE="${{ steps.issue-parser.outputs.issueparser_assignee }}"
          EPIC_ID="${{ steps.issue-parser.outputs.issueparser_parentKey }}"
          DUE_DATE="${{ steps.issue-parser.outputs.issueparser_dueDate }}"
          DESCRIPTION="${{ steps.md2jira.outputs.output-text }}"
          PRIORITY="${{ steps.issue-parser.outputs.issueparser_priority }}"
          ISSUE_TYPE="${{ steps.issue-parser.outputs.issueparser_type }}"

          ASSIGNEE_ACCOUNT_ID=""
          case "$ASSIGNEE" in
            "박예찬") ASSIGNEE_ACCOUNT_ID="712020:fc94f0fe-66d1-491c-9787-e96ae01b632c" ;;
            "허세라") ASSIGNEE_ACCOUNT_ID="712020:3284d418-06e0-45ac-9074-c5f407ed6620" ;;
            "왕혜찬") ASSIGNEE_ACCOUNT_ID="712020:6a5cb5bd-0786-4aed-ad02-11cb6f329cd6" ;;
            "") : ;; 
            *) echo "Unknown assignee name: '$ASSIGNEE' (will not set assignee)" ;;
          esac
          
          FIELDS=$(jq -nc \
            --arg parent "$EPIC_ID" \
            --arg description "$DESCRIPTION" \
            '{
              parent: { key: $parent },
              description: $description
            }'
          )
          [ -n "$ASSIGNEE_ACCOUNT_ID" ] && FIELDS=$(echo "$FIELDS" | jq --arg assignee "$ASSIGNEE_ACCOUNT_ID" -c '. + { assignee: { id: $assignee} }')
          [ -n "$DUE_DATE" ] && FIELDS=$(echo "$FIELDS" | jq --arg duedate "$DUE_DATE" -c '. + { duedate: $duedate }')
          [ -n "$PRIORITY" ] && FIELDS=$(echo "$FIELDS" | jq --arg priority "$PRIORITY" -c '. + { priority: { name: $priority} }')
          [ -n "$ISSUE_TYPE" ] && FIELDS=$(echo "$FIELDS" | jq --arg issuetype "$ISSUE_TYPE" -c '. + { issuetype: { name: $issuetype} }')
          FIELDS=$(echo "$FIELDS" | jq -c '.')
          echo "fields=$FIELDS" >> $GITHUB_OUTPUT
          

      - name: Create Issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: DF
          summary: '${{ github.event.issue.title }}'
          description: '${{ steps.md2jira.outputs.output-text }}'
          fields: '${{ steps.issue-fields.outputs.fields }}'

      - name: Log created issue
        run: echo "Jira Issue ${{ steps.issue-parser.outputs.parentKey }}/${{ steps.create.outputs.issue }} was created"

      - name: Checkout develop code
        uses: actions/checkout@v6
        with:
          ref: develop

      - name: Create branch with Ticket number
        run: |
          ISSUE_NUMBER="${{ steps.create.outputs.issue }}"
          ISSUE_TITLE="${{ steps.issue-parser.outputs.issueparser_branch }}"
          TYPE=${{ steps.issue-parser.outputs.issueparser_type }}
          TYPE_LOWER="$(echo "$TYPE" | tr '[:upper:]' '[:lower:]')"
          BRANCH_NAME="${TYPE_LOWER}/${ISSUE_NUMBER}-$(echo ${ISSUE_TITLE} | sed 's/ /-/g')"
          git checkout -b "${BRANCH_NAME}"
          git push origin "${BRANCH_NAME}"

      - name: Update issue title
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '[${{ steps.create.outputs.issue }}] ${{ github.event.issue.title }}'

      - name: Add comment with Jira issue link
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: 'Jira Issue Created: [${{ steps.create.outputs.issue }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.create.outputs.issue }})'
